language: node_js
node_js:
  - "7.7"
notifications:
  email:
    recipients:
      - harold@shinsato.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      - mtcodeschool:EsgrITV7bZSeDvlHeDj3eUHh#travis-ci
    on_success: always
    on_failure: always
